### ISSUE TITLE
Exception after leaving bot running for days

### ISSUE THREAD

**Issue by ramast** [GregHilston/Simple-Slack-Bot#22]
After leaving bot running for few days, I came to find it terminated with this exception.
Line numbers may not match existing code because I've added lines to ignore messages coming from slack that doesn't contain the key "message" (a dirty fix for the previous issue)

Traceback (most recent call last):
  File "app.py", line 21, in <module>
    main()
  File "app.py", line 17, in main
    simple_slack_bot.start()
  File "/home/skor/simple_slack_bot/simple_slack_bot.py", line 112, in start
    self.listen()
  File "/home/skor/simple_slack_bot/simple_slack_bot.py", line 165, in listen
    json_list = self._slack_client.rtm_read()
  File "/home/skor/simple_slack_bot/env/local/lib/python2.7/site-packages/slackclient/_client.py", line 123, in rtm_read
    json_data = self.server.websocket_safe_read()
  File "/home/skor/simple_slack_bot/env/local/lib/python2.7/site-packages/slackclient/_server.py", line 141, in websocket_safe_read
    data += "{0}\n".format(self.websocket.recv())
  File "/home/skor/simple_slack_bot/env/local/lib/python2.7/site-packages/websocket/_core.py", line 293, in recv
    opcode, data = self.recv_data()
  File "/home/skor/simple_slack_bot/env/local/lib/python2.7/site-packages/websocket/_core.py", line 310, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/home/skor/simple_slack_bot/env/local/lib/python2.7/site-packages/websocket/_core.py", line 323, in recv_data_frame
    frame = self.recv_frame()
  File "/home/skor/simple_slack_bot/env/local/lib/python2.7/site-packages/websocket/_core.py", line 357, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/home/skor/simple_slack_bot/env/local/lib/python2.7/site-packages/websocket/_abnf.py", line 336, in recv_frame
    self.recv_header()
  File "/home/skor/simple_slack_bot/env/local/lib/python2.7/site-packages/websocket/_abnf.py", line 286, in recv_header
    header = self.recv_strict(2)
  File "/home/skor/simple_slack_bot/env/local/lib/python2.7/site-packages/websocket/_abnf.py", line 371, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/home/skor/simple_slack_bot/env/local/lib/python2.7/site-packages/websocket/_core.py", line 427, in _recv
    return recv(self.sock, bufsize)
  File "/home/skor/simple_slack_bot/env/local/lib/python2.7/site-packages/websocket/_socket.py", line 93, in recv
    "Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.

**Comment by GregHilston** [comment]
Will look into at some point. Seems like its a common problem, see https://github.com/slackapi/python-slackclient/issues/127

**Comment by ramast** [comment]
Yes but in my case. the bot has started successfully and ran fine for a while ( at least one day).
Also our team is just 6 persons.

I am guessing the problem in our case is that connection eventually close for one reason or another.
We can just handle this exception and try to re-connect?

We can also keep counter for number of reconnect attempts so if x attempts has failed we can just terminate the program with appropriate error

**Comment by GregHilston** [comment]
@ramast That was just an example, I wasn't specifically trying to point out the high number of users in team or the startup.

Here's another example that might have been more closely related, https://github.com/gkbrk/hackchat/issues/1

**Comment by ramast** [comment]
According to that last link the bug has been fixed since 2015.
I am not trying to argue just trying to find a solution

**Comment by GregHilston** [comment]
Understood, I wasn't trying to be argumentative, sorry if I came off like that. Just did some quick google searches on the error you find. I added it to my TODO list when Graduate school lets up a little bit. I appreciate the bug reports and never want to seem aggressive ha

Thank you @ramast

**Comment by ramast** [comment]
Update: It's been running for over a week now without any problem.
I suppose the crash only happen when slack service goes offline. Can't be really sure
