### ISSUE TITLE
 __init__() got an unexpected keyword argument 'translate'

### ISSUE THREAD

**Issue by coltenkrauter** [GregHilston/Simple-Slack-Bot#34]
I am trying to run this in a docker container and I am having issues. Can you please help?

```
 Traceback (most recent call last):
   File "run.py", line 3, in <module>
   File "run.py", line 3, in <module>
     simple_slack_bot = SimpleSlackBot(debug=True)
   File "/usr/local/lib/python3.8/site-packages/simple_slack_bot/simple_slack_bot.py", line 60, in __init__
     simple_slack_bot = SimpleSlackBot(debug=True)
   File "/usr/local/lib/python3.8/site-packages/simple_slack_bot/simple_slack_bot.py", line 60, in __init__
     self._slackSocket = SlackSocket(self._SLACK_BOT_TOKEN, translate=False)
 TypeError: __init__() got an unexpected keyword argument 'translate'
     self._slackSocket = SlackSocket(self._SLACK_BOT_TOKEN, translate=False)
 TypeError: __init__() got an unexpected keyword argument 'translate'
```

Here is the code I am running. I have set the environment variable. 
```
from simple_slack_bot.simple_slack_bot import SimpleSlackBot

simple_slack_bot = SimpleSlackBot(debug=True)

@simple_slack_bot.register("message")
def pong_callback(request):
    if request.message and request.message.lower() == "ping":
        request.write("Pong")

def main():
    simple_slack_bot.start()

if __name__ == "__main__":
    main()
```

Python 3.8.0
pip freeze: 

```
certifi==2019.11.28
chardet==3.0.4
idna==2.8
pendulum==2.0.5
python-dateutil==2.8.1
pytzdata==2019.3
PyYAML==5.3.1
requests==2.22.0
simple-slack-bot==1.3.0
six==1.14.0
slacker==0.14.0
slacksocket==1.0.1
urllib3==1.25.8
websocket-client==0.48.0
```

**Comment by coltenkrauter** [comment]
It seems that the wrong version of one or more of the pip packages was being installed. I copied what was in your requirements.txt into mine and now it is working.

**Comment by GregHilston** [comment]
@coltenkrauter Glad to see someone using this project! While I haven't worked on it in a very long time, if you see any mistake, feel free to PR them into this repo!

I'd be happy to merge them in :) 

Also, when you have something working, I'd love to add your repo or a write up of your example to this repository!!!

**Comment by coltenkrauter** [comment]
Thanks @GregHilston!
